# Generated by Django 4.2.5 on 2023-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_receipt_expenses_receipt_income_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='income_receipts/'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
